# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v1.3.3
_src_path: gh:ThatXliner/pyt2
add_docs: true
author: Bryan Hu
email: thatxliner@gmail.com
is_app: true
module_name: scouting_tools
project_description: Team 3256's scouting utilities
project_name: Scouting Tools
pypi_name: scouting-tools
username: ThatXliner
